name: Build & Deploy

on:
  push:
    paths:
      - 'data/**'
      - 'index.html'
      - 'js/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 🔥 авто-индексация
      - name: Generate index.json
        run: |
          for dir in data/*/ ; do
            if [ -d "$dir" ]; then
              ls "$dir" | grep '.json' | grep -v 'index.json' > "$dir/index.json"
            fi
          done

      - name: Commit index.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/**/index.json
          git commit -m "auto update index" || echo "no changes"
          git push

      # 🔥 деплой
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

      - name: Deploy
        uses: actions/deploy-pages@v2
